import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const apiDir = path.join(root, "src", "app", "api");
const outFile = path.join(root, "electron", "route-table.generated.ts");

const METHODS = ["GET", "POST", "PATCH", "PUT", "DELETE"];

function walk(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.name === "route.ts") out.push(full);
  }
  return out;
}

function detectMethods(file) {
  const src = fs.readFileSync(file, "utf-8");
  return METHODS.filter((m) =>
    new RegExp(`export\\s+(?:async\\s+)?(?:function\\s+${m}\\b|const\\s+${m}\\b)`).test(src),
  );
}

function toRoute(file) {
  const rel = path.relative(apiDir, path.dirname(file)).split(path.sep).filter(Boolean);
  const routePath = "/api" + (rel.length ? "/" + rel.join("/") : "");
  const importPath = "@/app/api" + (rel.length ? "/" + rel.join("/") : "") + "/route";
  const paramNames = [];
  const pattern = rel
    .map((seg) => {
      const m = seg.match(/^\[(.+)\]$/);
      if (m) {
        paramNames.push(m[1]);
        return "([^/]+)";
      }
      return seg.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    })
    .join("/");
  const regex = "^/api" + (pattern ? "/" + pattern : "") + "$";
  return { routePath, importPath, paramNames, regex, methods: detectMethods(file) };
}

const routes = walk(apiDir)
  .map(toRoute)
  .filter((r) => r.methods.length > 0)
  .sort((a, b) => a.routePath.localeCompare(b.routePath));

const imports = routes
  .map((r, i) => {
    const named = r.methods.map((m) => `${m} as h${i}_${m}`).join(", ");
    return `import { ${named} } from "${r.importPath}";`;
  })
  .join("\n");

const entries = routes
  .map((r, i) => {
    const handlers = r.methods.map((m) => `${m}: toRouteHandler(h${i}_${m})`).join(", ");
    const params = r.paramNames.map((p) => `"${p}"`).join(", ");
    return `  {
    routePath: "${r.routePath}",
    regex: new RegExp(${JSON.stringify(r.regex)}),
    paramNames: [${params}],
    handlers: { ${handlers} },
  },`;
  })
  .join("\n");

const content = `// AUTO-GENERATED by scripts/gen-routes.mjs — do not edit.
import { toRouteHandler } from "./route-types";
import type { RouteEntry } from "./route-types";
${imports}

export { closeDb } from "@/lib/db/client";

export const ROUTES: RouteEntry[] = [
${entries}
];
`;

fs.writeFileSync(outFile, content, "utf-8");
console.log(`[gen-routes] wrote ${routes.length} routes -> ${path.relative(root, outFile)}`);
